---
- name: Build and Run Docker Image for Java App
  hosts: localhost
  become: true
  tasks:

    - name: Build Docker image
      community.docker.docker_image:
        name: jpetstoreapp_image
        tag: latest
        source: build
        build:
          path: "{{ playbook_dir }}"
    - name: Ensure old JPetStore container is removed
      docker_container:
        name: jpetstore
        state: absent
        
    - name: Run Docker container
      community.docker.docker_container:
        name: jpetstoreapp_container
        image: jpetstoreapp_image:latest
        container_default_behavior: compatibility
        state: started
        ports:
          - "8080:8080"
