---
   - name: Deploy JPetStore Docker container locally
     hosts: local
     become: yes
     tasks:
       - name: Remove conflicting containerd.io package
         apt:
           name:
             - containerd.io
             - containerd
             - docker-ce
             - docker-ce-cli
           state: absent
           purge: yes
         ignore_errors: yes

       - name: Clean up package cache
         apt:
           autoclean: yes
           autoremove: yes
         ignore_errors: yes

       - name: Fix broken dependencies
         apt:
           name: "*"
           state: fixed
         ignore_errors: yes

       - name: Install Docker
         apt:
           name: docker.io
           state: present
           update_cache: yes

       - name: Install python3-pip
         apt:
           name: python3-pip
           state: present
           update_cache: yes

       - name: Install Docker SDK for Python
         pip:
           name: docker
           state: present
           executable: pip3

       - name: Start Docker service
         service:
           name: docker
           state: started
           enabled: yes

       - name: Add Jenkins user to docker group
         user:
           name: jenkins
           groups: docker
           append: yes

       - name: Ensure old JPetStore container is removed
         docker_container:
           name: jpetstore
           state: absent

       - name: Run JPetStore container
         docker_container:
           name: jpetstore
           image: "{{ docker_image }}"
           state: started
           ports:
             - "8080:8080"
           restart_policy: always
